# Generated by Django 5.1.13 on 2025-12-09 16:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('color', models.CharField(help_text='Color HTML', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional')),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('POL', 'Política'), ('DEP', 'Deportes'), ('CUT', 'Cultura')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('importancia', models.IntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.PositiveSmallIntegerField(choices=[(1, 'Administrador'), (2, 'Autor'), (3, 'Usuario')], default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo', max_length=100, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('edad', models.PositiveIntegerField(default=18, null=True)),
                ('sueldo', models.DecimalField(decimal_places=2, default=1200.0, max_digits=7)),
                ('es_redactor', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_autores/')),
                ('usuariosesion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, unique=True)),
                ('contenido', models.TextField()),
                ('visitas', models.PositiveIntegerField(default=0)),
                ('publicado_en', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodicoweb.autor')),
                ('seccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='periodicoweb.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='ArticuloEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevancia', models.FloatField(default=1.0)),
                ('fecha_asignacion', models.DateField(null=True)),
                ('comentario', models.TextField(blank=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulo_etiquetas', to='periodicoweb.articulo')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodicoweb.etiqueta')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('lugar', models.CharField(blank=True, max_length=50)),
                ('fecha', models.DateField()),
                ('capacidad', models.PositiveIntegerField(default=50)),
                ('articulos', models.ManyToManyField(blank=True, to='periodicoweb.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(help_text='Solo números', max_length=15)),
                ('fecha_nacimiento', models.DateField(auto_now_add=True, null=True)),
                ('hora_favorita', models.TimeField(auto_now=True)),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='periodicoweb.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('mensaje', models.CharField(max_length=100)),
                ('destacado', models.BooleanField(default=False)),
                ('articulo_principal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='periodicoweb.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('es_premium', models.BooleanField(default=False)),
                ('puntos', models.IntegerField(default=0)),
                ('usuariosesion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('preferencia_hora', models.TimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='periodicoweb.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateField(auto_now_add=True)),
                ('usuarios', models.ManyToManyField(blank=True, to='periodicoweb.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('puntuacion', models.FloatField(default=0.0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodicoweb.articulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodicoweb.usuario')),
            ],
        ),
    ]
