# Generated by Django 5.1.13 on 2025-11-08 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicoweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articuloetiqueta',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulo_etiquetas', to='periodicoweb.articulo'),
        ),
    ]
