# Generated by Django 5.1.13 on 2025-11-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicoweb', '0002_alter_articuloetiqueta_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='autores_fotos/'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='es_redactor',
            field=models.BooleanField(default=True),
        ),
    ]
