# Generated by Django 5.1.13 on 2025-12-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodicoweb', '0003_autor_foto_alter_autor_es_redactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_autores/'),
        ),
    ]
